# Choose language
language: node_js
# choose version of node
node_js:
  - 8
# Use ligth version of linux os
dist: trusty
# Specify services
services:
  - mongodb
  - redis-server
# Declare env variables
env:
  - NODE_ENV=ci PORT=3000
# Cache static folders
cache:
  directories:
  - node_modules
  - client/node_modules
# run commands to build prod version
install:
  - npm install
  - npm build
# npm start with no hang up and allowing using command line/wait for 3 seconds for server start
script:
  - nohup npm start &
  - sleep 3
  - npm run test